#!/bin/bash

THREADS=6
NB_ITERATIONS=5000000

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nsss.abs\
    -d strategies/info_abs_test/ca-nsss.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nooo.abs\
    -d strategies/info_abs_test/ca-nooo.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nees.abs\
    -d strategies/info_abs_test/ca-nees.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-neeo.abs\
    -d strategies/info_abs_test/ca-neeo.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-npeo.abs\
    -d strategies/info_abs_test/ca-npeo.strat

#BIG ABS
./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nsss-b.abs\
    -d strategies/info_abs_test/ca-nsss-b.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nooo-b.abs\
    -d strategies/info_abs_test/ca-nooo-b.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-nees-b.abs\
    -d strategies/info_abs_test/ca-nees-b.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-neeo-b.abs\
    -d strategies/info_abs_test/ca-neeo-b.strat

./cfrm --seed 0 -t holdem -g ../../games/holdem.nolimit.2p.reverse_blinds.game\
    -c cluster -a potrel -n 1 -r 99999 -k 120 --threads $THREADS\
    -u $NB_ITERATIONS -m abstractions/infoabs_test/ca-npeo-b.abs\
    -d strategies/info_abs_test/ca-npeo-b.strat
